<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Failed suite [登录]">
  <test name="登录-deviceId为空(failed)">
    <groups>
      <run>
        <include name="exception"/>
      </run>
    </groups>
    <classes>
      <class name="com.suite.CaseLogin">
        <methods>
          <include name="beforeClass"/>
          <include name="beforeClass"/>
          <include name="afterMethod"/>
          <include name="afterMethod"/>
          <include name="CaseLogin002" invocation-numbers="0"/>
          <include name="afterClass"/>
          <include name="afterClass"/>
          <include name="beforeMethod"/>
          <include name="beforeMethod"/>
        </methods>
      </class> <!-- com.suite.CaseLogin -->
    </classes>
  </test> <!-- 登录-deviceId为空(failed) -->
</suite> <!-- Failed suite [登录] -->
